version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: stock_ai_postgres_prod
    environment:
      POSTGRES_DB: stock_ai
      POSTGRES_USER: stock_ai_user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - stock_ai_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U stock_ai_user -d stock_ai"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: stock_ai_redis_prod
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - stock_ai_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  # Database Migration Service (runs once)
  db-migrate:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: stock_ai_migrate
    environment:
      - DATABASE_URL=postgresql+asyncpg://stock_ai_user:${POSTGRES_PASSWORD}@postgres:5432/stock_ai
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - stock_ai_network
    command: ["python3", "-m", "alembic", "upgrade", "head"]
    restart: "no"

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: stock_ai_backend_prod
    environment:
      - DATABASE_URL=postgresql+asyncpg://stock_ai_user:${POSTGRES_PASSWORD}@postgres:5432/stock_ai
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=${JWT_SECRET}
      - FERNET_KEY=${FERNET_KEY}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - ZERODHA_API_KEY=${ZERODHA_API_KEY}
      - ZERODHA_API_SECRET=${ZERODHA_API_SECRET}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_TLS=${SMTP_TLS}
      - SMTP_SSL=${SMTP_SSL}
      - FROM_EMAIL=${FROM_EMAIL}
      - FROM_NAME=${FROM_NAME}
      - OTP_EXPIRE_MINUTES=${OTP_EXPIRE_MINUTES}
      - OTP_LENGTH=${OTP_LENGTH}
      - ENVIRONMENT=production
      - BACKEND_CORS_ORIGINS=${BACKEND_CORS_ORIGINS}
      - FRONTEND_URL=${FRONTEND_URL}
      - WS_URL=ws://localhost:8000
      - NEXT_PUBLIC_WS_URL=ws://localhost:8000
    ports:
      - "8000:8000"
    depends_on:
      db-migrate:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - stock_ai_network
    restart: unless-stopped

  # Frontend (React)
  frontend:
    build:
      context: ./frontend-react
      dockerfile: Dockerfile
    container_name: stock_ai_frontend_prod
    environment:
      - VITE_API_URL=http://localhost:8000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - stock_ai_network
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:

networks:
  stock_ai_network:
    driver: bridge 